Prefix: '&8[&dNxt&bGen&8]&r: '

Names:
 - 'Laura884'
 - 'Laura8827'
 - 'RAR_E'
 - 'HypersMC'
 - 'HALD91'
Owner:
 - 'Laura884'
 - 'Laura8827'
 - 'RAR_E'
Admin:
 - 'HypersMC'
Dev:
 - 'HALD91'
Whitelist:
 - 'Laura884'
 - 'Laura8827'
 - 'RAR_E'
 - 'HypersMC'